version: "3.8"

volumes:
  postgres:

services:
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data/
    env_file:
      - app/tests/.env.local
