version: "3.8"

volumes:
  postgres:

services:
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data/
    env_file:
      - app/tests/.env.local

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    ports:
      - "2181:2181"
    env_file:
      - app/tests/.env.local

  kafka:
    image: confluentinc/cp-enterprise-kafka:latest
    hostname: kafka
    depends_on:
      - zookeeper
    ports:
      - "29092:29092"
    env_file:
      - app/tests/.env.local

  schemaregistry:
    image: confluentinc/cp-schema-registry:latest
    hostname: schemaregistry
    container_name: schemaregistry
    depends_on:
      - zookeeper
      - kafka
    ports:
      - "8081:8081"
    env_file:
      - app/tests/.env.local

  connect:
    image: confluentinc/cp-kafka-connect:5.5.3
    hostname: connect
    container_name: connect
    depends_on:
      - zookeeper
      - kafka
      - schemaregistry
    ports:
      - "8083:8083"
    env_file:
      - app/tests/.env.local

  kafka-topic-init:
    image: pranavt61/kafka-topic-init:latest
    depends_on:
      - kafka
    env_file:
      - app/tests/.env.local
    volumes:
      - ./app/tests/helpers/:/topics/
    restart: on-failure
