name: PR CI

# For all pushes to the main branch run the tests and push the image to the
# GitHub registry under an edge tag so we can use it for the nightly
# integration tests
on:
  pull_request:
    branches: main

jobs:
  docker:
    runs-on: ubuntu-latest
    env:
      DOCKER_TARGET: test
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build the stack
        run: docker-compose -f docker-compose.yml up -d

      - name: Check running containers
        run: docker-compose -f docker-compose.yml ps

      - name: Run test suite
        continue-on-error: true
        run: |
          sleep 60
          docker-compose exec -T filter-registration pytest

      - name: Some debug steps that need to happen
        continue-on-error: true
        run: |
          docker-compose exec -T filter-registration curl http://connect:8083/connectors
          docker-compose exec -T filter-registration curl http://connect:8083/connectors/EventRegistrationsSink
